apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: my-cluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - null
    services:
      cidrBlocks:
        - null
    serviceDomain: ""
  topology:
    classRef:
      name: vates-rhel-from-scratch
    version: ""
    variables:
      - name: controlPlaneEndpoint
        value:
          host: ""
          port: 0
          subnet: 0
      - name: vmNamePrefix
        value: ""
      - name: controlPlaneLB
        value: ""
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: worker-from-scratch
          name: worker-md-0
          replicas: 2
